[
    {
        id: 1,
        name: "Banana",
        category: "Fruits",
        description: "A sweet, yellow fruit with a soft texture.",
        price: 0.25,
        image: "https://dummyimage.com/400x400/ffe135/000000&text=Banana",
    },
    {
        id: 2,
        name: "Eggs",
        category: "Proteins",
        description: "A protein-rich food that is commonly used in many recipes.",
        price: 2.5,
        image: "https://dummyimage.com/400x400/ffffff/000000&text=Eggs",
    },
    {
        id: 3,
        name: "Milk",
        category: "Dairy",
        description: "A white liquid that is rich in calcium and used in many recipes.",
        price: 3,
        image: "https://dummyimage.com/400x400/ffffff/000000&text=Milk",
    },
    {
        id: 4,
        name: "Bread",
        category: "Grains",
        description: "A staple food made from flour, water, and yeast.",
        price: 2,
        image: "https://dummyimage.com/400x400/ffffff/000000&text=Bread",
    },
    {
        id: 5,
        name: "Chicken",
        category: "Meat",
        description: "A common poultry that is a good source of protein.",
        price: 8,
        image: "https://dummyimage.com/400x400/ffffff/000000&text=Chicken",
    },
    {
        id: 6,
        name: "Rice",
        category: "Grains",
        description: "A staple food made from the seeds of the rice plant.",
        price: 1.5,
        image: "https://dummyimage.com/400x400/ffffff/000000&text=Rice",
    },
    {
        id: 7,
        name: "Potatoes",
        category: "Vegetables",
        description: "A starchy root vegetable that is commonly used in many recipes.",
        price: 0.5,
        image: "https://dummyimage.com/400x400/ffffff/000000&text=Potatoes",
    },
    {
        id: 8,
        name: "Tomatoes",
        category: "Vegetables",
        description: "A juicy, red fruit that is commonly used in many recipes.",
        price: 1,
        image: "https://dummyimage.com/400x400/ffffff/000000&text=Tomatoes",
    },
    {
        id: 9,
        name: "Salmon",
        category: "Seafood",
        description: "A popular fatty fish that is high in omega-3 fatty acids.",
        price: 12,
        image: "https://dummyimage.com/400x400/ffffff/000000&text=Salmon",
    },
    {
        id: 10,
        name: "Cheese",
        category: "Dairy",
        description: "A dairy product made from milk and often used in cooking and as a topping.",
        price: 4,
        image: "https://dummyimage.com/400x400/ffffff/000000&text=Cheese",
    },
    {
        id: 11,
        name: "Apple",
        category: "Fruit",
        description: "A round fruit with firm, juicy flesh and typically red, yellow, or green skin. Apples are high in fiber, vitamin C, and various antioxidants.",
        price: 0.5,
        image: "https://dummyimage.com/400x400/ff9900/ffffff&text=Apple"
    },
    {
        id: 12,
        name: "Carrots",
        category: "Vegetables",
        description: "A crunchy root vegetable that is high in vitamin A.",
        price: 1,
        image: "https://dummyimage.com/400x400/ffffff/000000&text=Carrots",
    },
    {
        id: 13,
        name: "Yogurt",
        category: "Dairy",
        description: "A fermented dairy product that is high in protein and good bacteria.",
        price: 3.5,
        image: "https://dummyimage.com/400x400/ffffff/000000&text=Yogurt",
    },
    {
        id: 14,
        name: "Spinach",
        category: "Vegetables",
        description: "A leafy green vegetable that is high in iron and other nutrients.",
        price: 2.5,
        image: "https://dummyimage.com/400x400/ffffff/000000&text=Spinach",
    },
    {
        id: 15,
        name: "Ground beef",
        category: "Meat",
        description: "A versatile meat that is often used in many recipes.",
        price: 6,
        image: "https://dummyimage.com/400x400/ffffff/000000&text=Ground+beef",
    },
    {
        id: 16,
        name: "Pasta",
        category: "Grains",
        description: "A staple food made from wheat flour that is commonly used in many recipes.",
        price: 2.5,
        image: "https://dummyimage.com/400x400/ffffff/000000&text=Pasta",
    },
    {
        id: 17,
        name: "Onions",
        category: "Vegetables",
        description: "A pungent bulb vegetable that is commonly used in many recipes.",
        price: 1,
        image: "https://dummyimage.com/400x400/ffffff/000000&text=Onions",
    },
    {
        id: 18,
        name: "Oranges",
        category: "Fruits",
        description: "A sweet, juicy fruit that is high in vitamin C.",
        price: 0.5,
        image: "https://dummyimage.com/400x400/ffffff/000000&text=Oranges",
    },
    {
        id: 19,
        name: "Salad greens",
        category: "Vegetables",
        description: "A variety of leafy greens that are commonly used in salads.",
        price: 3,
        image: "https://dummyimage.com/400x400/ffffff/000000&text=Salad+greens",
    },
    {
        id: 20,
        name: "Peanut butter",
        category: "Spreads",
        description: "A spread made from ground peanuts that is high in protein and healthy fats.",
        price: 4,
        image: "https://dummyimage.com/400x400/ffffff/000000&text=Peanut+butter",
    },
    {
        id: 21,
        name: "Canned tomatoes",
        category: "Canned goods",
        description: "A canned product made from tomatoes that is commonly used in many recipes.",
        price: 1.5,
        image: "https://dummyimage.com/400x400/ffffff/000000&text=Canned+tomatoes",
    },
]
